### ISSUE TITLE
CORS Setting

### ISSUE THREAD

**Issue by ryo-is** [uji/ness-api-function#1]
## 何をしてほしいか

CORSの設定をしてほしい。
ここらへんが参考になるかもです。(自分でやろうとして挫折した…)
https://gqlgen.com/recipes/cors/

![image](https://user-images.githubusercontent.com/32923565/92609769-e8808b80-f2f1-11ea-9e64-77429bcdc00c.png)

**Comment by uji** [comment]
@ryo-is 全オリジン許可するようにしました
e325137518c466fcec9c194fed8292874f49f47e
